version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: bind
        source: ./dgraph
        target: /dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:latest
    volumes:
      - type: bind
        source: ./dgraph
        target: /dgraph
    ports:
      - 8181:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --whitelist 172.17.0.0:172.20.0.0 --my=server:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    volumes:
      - type: bind
        source: ./dgraph
        target: /dgraph
    ports:
      - 9000:8000
    command: dgraph-ratel
